[package]
name = "transit"
version = "0.2.0"
authors = ["crhino <piraino.chris@gmail.com>"]

description = "Send and receive types over UDP packets."
readme = "./README.md"
repository = "https://github.com/crhino/transit"
keywords = ["udp", "network"]
license = "BSD-3-Clause"

[dependencies]
serde = "*"

rmp = { version = "*", optional = true }
rmp-serde = { version = "*", optional = true }
serde_json = { version = "*", optional = true }

[dev-dependencies]
serde_macros = "*"

[features]
default = ["rmp", "rmp-serde"]
json = ["serde_json"]
